### ISSUE TITLE
Dockerhub image fails start postgres

### ISSUE THREAD

**Issue by brandonaaskov** [phocean/dockerfile-debian-metasploit#11]
## When it's successful...
If I clone the repo, and build the image directly, and then run it, it works.
```
docker build -t msf .
docker run --rm -it msf
```

![Success](https://user-images.githubusercontent.com/445778/130530032-eeb45936-92a8-4552-ae55-16f717e06630.png)

## When it's _not_ successful...
However, if I pull the image from Dockerhub, that throws an error around starting Postgres:
```
docker pull phocean/msf
docker run --rm -it phocean/msf
```

![Fail](https://user-images.githubusercontent.com/445778/130530135-252477e1-99ac-42ef-8c84-b24341a924f9.png)

## Maybe it's me?
There's a very good chance I'm just missing something fundamental here, but I had the same thing happen on my Mac which is why I switched to a debian-based VM to try it and got the same result.

**Comment by s1nglethr3ad** [comment]
Same issue.

**Comment by r0mdau** [comment]
@s1nglethr3ad @brandonaaskov I have forked and used a Github Action to build and push the image.

Can you check using docker image : r0mdau/msf ?

If it works, we wait for @phocean to merge this PR #12 
I've already contributed to this repo.

**Comment by aviadhahami** [comment]
I didn't inspect the layers to verify anything shady was brought in, but msf-wise I can confirm this works 👍

**Comment by gardnerapp** [comment]
When I try to build the image from scratch I get an Error while the Racc gem is being installed

**Comment by r0mdau** [comment]
@gardnerapp can you copy paste your logs ?
