### ISSUE TITLE
/usr/local/bin/init.sh: line 5: /etc/init.d/postgresql: No such file or directory

### ISSUE THREAD

**Issue by Rourke101** [phocean/dockerfile-debian-metasploit#13]
I just pulled the latest version and got this:

```
docker run --rm -it phocean/msf
/usr/local/bin/init.sh: line 5: /etc/init.d/postgresql: No such file or directory
```

**Comment by r0mdau** [comment]
Duplicates #11.
Please try with image "r0mdau/msf" while waiting for the PR to be merged.
Better option is to build yourself the image.

**Comment by gardnerapp** [comment]
How do I build the image, sorry very new to docker.

**Comment by gardnerapp** [comment]
I tried cloning your repo but when I run the msfconsole it says there isn't enough memory. But I checked my system memory and I think I have enough space

**Comment by r0mdau** [comment]
@gardnerapp to build this image : 
`docker build -t phocean/msf .`

**Comment by phocean** [comment]
Fixed with last update.
