### ISSUE TITLE
can't run

### ISSUE THREAD

**Issue by kevinchugh** [phocean/dockerfile-debian-metasploit#5]
hi, trying to follow directions i get this

`docker run --rm -i -t -p 9990-9999:9990-9999 -v /home/<USER>/.msf4:/root/.msf4 -v /tmp/msf:/tmp/data --name msf phocean/msf`

`bash: USER: No such file or directory`

**Comment by kevinchugh** [comment]
also can't build FWIW

**Comment by kevinchugh** [comment]
accidentally clicked close

**Comment by r0mdau** [comment]
Hi,

You have to replace \<USER\> by your current username or simply by $USER.

**Comment by phocean** [comment]
Thanks @r0mdau. This is not a bug, but I fixed the README to make it more natural.

**Comment by kevinchugh** [comment]
thank you!
