### ISSUE TITLE
how to add msfrpc?

### ISSUE THREAD

**Issue by smarttang** [phocean/dockerfile-debian-metasploit#6]
RT?

**Comment by phocean** [comment]
??

Clarify...

**Comment by smarttang** [comment]
I want add and running msfrpc service in docker...
emmm... I try..

**Comment by phocean** [comment]
`msfrpc` binary is already there and working, so I don't see any issue.
I am closing it unless you come back with technical details and debug output.

**Comment by smarttang** [comment]
是这样的，我的意思是，您这个镜像是否能够增加msfrpc的服务启动，在这个版本上，msfrpc的db.hosts不可用，我测试过了。我只是想说这个。。。

This is the case, I mean, whether your image can increase the service startup of msfrpc. In this version, db.hosts of msfrpc is not available, I have tested it. I just want to say this. . .
