### ISSUE TITLE
How to add  ifconfig and update NMAP

### ISSUE THREAD

**Issue by Ashutosh-Kukreti** [phocean/dockerfile-debian-metasploit#8]
Hi,
Can you pleased add all the net-tools to the image including ifconfig ,ping etc.
I tried the `apt install net-tools` command but it didn't work.
Also please update nmap to 7.80.

**Comment by phocean** [comment]
The nmap version should probably be fixed with the much overdue update that I just pushed.

I do not wish to install net-tools as it is not a virtual machine : I want to keep it as small as possible, and as you share the network stack with the host, I see no need for that.
